### ISSUE TITLE
Links werden im Browser statt in der App geöffnet

### ISSUE THREAD

**Issue by LeTobi** [phlhg/tippspiel#10]
Das Verteilungssystem mit capability urls regt zur Nutzung im Browser an anstatt die App zu fördern.
Dies ist besonders nachteilig in kombination mit dem "installieren"-banner

**Comment by phlhg** [comment]
Die Entscheidung, ob ein Link im PWA oder im Browser geöffnet wird, wird durch das Betriebssystem (Android, iOS) getätigt. 
Im Webmanifest sind zwar einige Properties ("intend_filters","scope",...) dafür konfiguriert, aber diese werden nicht immer beachtet.

**Comment by phlhg** [comment]
Mit Commit 3bd59fa erkennt Android Chrome Tippspiel nun als PWA. Nach dem installieren können Links nun direkt in der App geöffnet werden. Diese Funktion existiert allerdings nach meinem Wissen bei Android Firefox und iOS Safari nicht, wodurch das Problem dort nicht behoben werden kann.
