### ISSUE TITLE
Inkonsistente Client-Zustände über mehrere Tabs

### ISSUE THREAD

**Issue by LeTobi** [phlhg/tippspiel#11]
Wenn mehrere Instanzen des Tippspiels geöffnet sind, werden gewisse änderungen nicht erkannt.
Wichtiger Fall:
Wenn das spiel unmittelbar installiert wird und anschliessend der Bestätigungslink verwendet wird, erkennt die App den login nicht ohne seiten-refresh

**Comment by phlhg** [comment]
Das Problem wurde mit LocalStorage Synchronization in Commit 3603817 behoben
