### ISSUE TITLE
0-0 Bei anstehenden Spielen

### ISSUE THREAD

**Issue by LeTobi** [phlhg/tippspiel#13]
Die Detailansicht von Spielen, die in der Zukunft liegen sollten das Datum anzeigen anstatt 0:0. Die Anzeige von 0:0 kann als Tipp fehlinterpretiert werden und kann Nutzer frustrieren, die anders getippt haben.

**Comment by phlhg** [comment]
Die Anzeige zeigt nun - : - an, falls das Spiel noch nicht beendet wurde.
