### ISSUE TITLE
DuckDuckGo Browser wird falsch erkannt (PWA-Support)

### ISSUE THREAD

**Issue by LeTobi** [phlhg/tippspiel#15]
Das Installieren-Banner wird auf gewissen Mobile-Browsern auch nach der Installation angezeigt.
(DuckDuckGo-Browser)

**Comment by phlhg** [comment]
Der DuckDuckGo Browser unterstützt PWAs nicht. Es wird stattdessen ein Lesezeichen auf dem Homebildschirm erstellt, welches den Browser öffnet - Dieser wird natürlich nicht als PWA erkannt und das Pop-Up erscheint.

Das eigentliche Problem liegt in der Erkennung des Browsers: Offenbar hält der Tippspiel-Client den DuckDuckGo Browser für einen Browser, welcher PWAs unterstützt. Dies sollte behoben werden können.
