### ISSUE TITLE
Nutzer wegleitung

### ISSUE THREAD

**Issue by LeTobi** [phlhg/tippspiel#9]
Es ist nicht offensichtlich, wo man Tipps abgibt. Es fehlt eine Anzeige: "hier den Tipp abgeben"

**Comment by phlhg** [comment]
Werde den Text "Du hast noch nicht getippt" zu "Klicke hier um zu tippen" änderen.

**Comment by phlhg** [comment]
Implementiert mit Commit 72cef7d
